# Generated by Django 5.0.1 on 2024-02-16 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player_extra_team_extra_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('favorite', models.ManyToManyField(blank=True, related_name='fa_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
